sudo: required
language: bash
services:
  - docker

before_install:
  - docker build -t libyui-image .
script:
  - docker run -it --rm -e COVERALLS_TOKEN="$COVERALLS_TOKEN" -e TRAVIS_JOB_ID="$TRAVIS_JOB_ID" libyui-image ci-tasks

