
# See https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions

name: CI

on: [push, pull_request]

jobs:
  Package:
    runs-on: ubuntu-latest
    container: registry.opensuse.org/devel/libraries/libyui/sle-15/sp3/containers/libyui-devel:latest

    steps:

    - name: Git Checkout
      uses: actions/checkout@v2

    # just for easier debugging...
    - name: Inspect Installed Packages
      run: rpm -qa | sort

    # monkey-patch obs-service-source_validator.rpm to avoid "ERROR: we
    # support  EITHER _multibuild OR multiple spec files. Do not add both"
    # This is easier than adding a repo containing a fixed RPM.
    # For details see
    # https://github.com/openSUSE/obs-service-source_validator/issues/79
    - name: update obs-service-source_validator
      run: rm /usr/lib/obs/service/source_validators/*-multibuild_xor_multispec

    - name: Packages Build And Install
      run:  ./ci-tasks
